<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c0271d32-8ce5-4678-a233-0a377adcf7e3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Payments\Payments.Api\Payments.Api.csproj" />
    <ProjectReference Include="..\..\src\PaymentSwitch\PaymentSwitch.Worker\PaymentSwitch.Worker.csproj" />
    <ProjectReference Include="..\..\src\PaymentSwitch\PaymentSwitch.Processor\PaymentSwitch.Processor.csproj" />
    <ProjectReference Include="..\..\src\ClientProfiles\ClientProfiles.Api\ClientProfiles.Api.csproj" />
    <ProjectReference Include="..\..\src\Identity\Identity.Client\Identity.Client.Api\Identity.Client.Api.csproj" />
    <ProjectReference Include="..\..\src\PayableServices\PayableServices.Api\PayableServices.Api.csproj" />
  </ItemGroup>

</Project>
