<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.RabbitMQ\Infrastructure.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\Utilities\Utilities.Responses\Utilities.Responses.csproj" />
    <ProjectReference Include="..\..\ExternalConnections\ExternalConnections.PaymentOperators\ExternalConnections.PaymentOperators.csproj" />
    <ProjectReference Include="..\PaymentSwitch.Contracts\PaymentSwitch.Contracts.csproj" />
    <ProjectReference Include="..\PaymentSwitch.Messaging\PaymentSwitch.Messaging.csproj" />
  </ItemGroup>
</Project>
