<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7959f0dc-a864-4ff6-81ff-2afb0c65553c</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.RabbitMQ\Infrastructure.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\ExternalConnections\ExternalConnections.PaymentOperators\ExternalConnections.PaymentOperators.csproj" />
    <ProjectReference Include="..\PaymentSwitch.Messaging\PaymentSwitch.Messaging.csproj" />
  </ItemGroup>
</Project>
